name: Build OpenWrt Theme Package

on:
  workflow_dispatch:
    inputs:
      theme_url:
        description: 'URL of the OpenWrt theme file to clone'
        required: true
        default: 'https://github.com/example/openwrt-theme.git'
      architectures:
        description: 'Comma-separated list of architectures to build'
        required: true
        default: 'x86_64,armv7,mipsel'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup OpenWrt environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++ libc6-dev libncurses5-dev libssl-dev libz-dev
          sudo apt-get install -y subversion git gawk wget diffstat unzip curl python3 python3-distutils
          sudo apt-get install -y rsync file liblzma-dev

      - name: Clone OpenWrt repository
        run: |
          git clone https://github.com/openwrt/openwrt.git openwrt-project

      - name: Clone theme repository
        run: |
          cd openwrt-project
          git clone ${{ github.event.inputs.theme_url }} package/luci-theme-peditx

      - name: Update and install feeds
        run: |
          cd openwrt-project
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure OpenWrt build
        run: |
          cd openwrt-project
          make defconfig
          echo "CONFIG_PACKAGE_luci-theme-peditx=y" >> .config

      - name: Build theme package only
        run: |
          cd openwrt-project
          make package/luci-theme-peditx/compile

      - name: Find and Zip all .ipk files for luci-theme-peditx
        run: |
          cd openwrt-project
          # Find all .ipk files related to luci-theme-peditx
          IPK_FILES=$(find bin/packages/*/luci-theme-peditx*.ipk)
          if [ ! -z "$IPK_FILES" ]; then
            # Zip all the .ipk files
            zip -r openwrt-luci-theme-peditx.ipk.zip $IPK_FILES
          else
            echo "No .ipk files found for luci-theme-peditx."
            exit 1
          fi

      - name: Upload the theme .ipk artifact
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-luci-theme-peditx
          path: openwrt-project/openwrt-luci-theme-peditx.ipk.zip
