name: Build OpenWrt Package

on:
  workflow_dispatch:
    inputs:
      project_url:
        description: 'URL of the OpenWrt theme repository'
        required: true
        default: 'https://github.com/example/openwrt-theme'
      architectures:
        description: 'Comma-separated list of architectures to build'
        required: true
        default: 'x86_64,armv7,mipsel'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup OpenWrt environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++ libc6-dev libncurses5-dev libssl-dev libz-dev
          sudo apt-get install -y subversion git gawk wget diffstat unzip curl python3 python3-distutils
          sudo apt-get install -y rsync file liblzma-dev

      - name: Clone OpenWrt repository
        run: |
          git clone https://github.com/openwrt/openwrt.git openwrt-project
          cd openwrt-project
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add custom theme repository
        run: |
          cd openwrt-project
          echo "src-git luci-theme ${{ github.event.inputs.project_url }}" >> feeds.conf.default
          ./scripts/feeds update luci-theme
          ./scripts/feeds install luci-theme

      - name: Build OpenWrt for specified architectures
        run: |
          cd openwrt-project
          make defconfig
          IFS=',' read -r -a ARCH_ARRAY <<< "${{ github.event.inputs.architectures }}"
          for ARCH in "${ARCH_ARRAY[@]}"; do
            make -j$(nproc) V=s
          done

      - name: Zip .ipk files
        run: |
          cd openwrt-project
          IPK_FILES=$(find bin/packages/*/*.ipk)
          if [ ! -z "$IPK_FILES" ]; then
            zip -r openwrt-ipks.zip $IPK_FILES
          else
            echo "No .ipk files found."
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-ipks
          path: openwrt-project/openwrt-ipks.zip
