name: Build OpenWrt Package

on:
  workflow_dispatch:
    inputs:
      theme_url:
        description: 'URL of the OpenWrt theme file to clone'
        required: true
        default: 'https://github.com/example/openwrt-theme.git'
      architectures:
        description: 'Comma-separated list of architectures to build'
        required: true
        default: 'x86_64,armv7,mipsel'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup OpenWrt environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++ libc6-dev libncurses5-dev libssl-dev libz-dev
          sudo apt-get install -y subversion git gawk wget diffstat unzip curl python3 python3-distutils
          sudo apt-get install -y rsync file liblzma-dev

      - name: Clone OpenWrt repository
        run: |
          git clone https://github.com/openwrt/openwrt.git openwrt-project
          cd openwrt-project
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Clone theme repository with authentication
        run: |
          cd openwrt-project
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com".insteadOf "https://github.com"
          git clone ${{ github.event.inputs.theme_url }} package/luci-theme-peditx

      - name: Configure OpenWrt build
        run: |
          cd openwrt-project
          make defconfig
          echo "CONFIG_PACKAGE_luci-theme-peditx=y" >> .config

      - name: Build OpenWrt for specified architectures
        run: |
          cd openwrt-project
          IFS=',' read -r -a ARCH_ARRAY <<< "${{ github.event.inputs.architectures }}"
          for ARCH in "${ARCH_ARRAY[@]}"; do
            make -j$(nproc) V=s
          done

      - name: Zip .ipk files
        run: |
          cd openwrt-project
          IPK_FILES=$(find bin/packages/*/*.ipk)
          if [ ! -z "$IPK_FILES" ]; then
            zip -r openwrt-ipks.zip $IPK_FILES
          else
            echo "No .ipk files found."
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-ipks
          path: openwrt-project/openwrt-ipks.zip
