name: Build app for OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Required Tools
      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev \
            gawk git gettext libssl-dev xsltproc wget unzip python3 python3-distutils zip
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      # Step 3: Read Config File and Extract Values
      - name: Read Config File
        id: config
        run: |
          export REPOSITORY=$(yq '.repository' config.yaml)
          export PACKAGE_NAME=$(yq '.package_name' config.yaml)
          export ARCHITECTURES=$(yq '.architectures | join(",")' config.yaml)
          echo "repository=$REPOSITORY" >> $GITHUB_ENV
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "architectures=$ARCHITECTURES" >> $GITHUB_ENV

      # Debug step for confirmation
      - name: Debug Config Values
        run: |
          echo "Repository: ${{ env.REPOSITORY }}"
          echo "Package Name: ${{ env.PACKAGE_NAME }}"
          echo "Architectures: ${{ env.ARCHITECTURES }}"

      # Step 4: Clone the Package Repository
      - name: Clone Package Repository
        run: |
          if [ -z "$REPOSITORY" ]; then
            echo "Error: Repository URL is not defined. Check your config.yaml file."
            exit 1
          fi
          git clone $REPOSITORY ./package-src

      # Remaining steps unchanged...
