name: Build OpenWrt Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Step 2: Set up dependencies
    - name: Set up dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip curl
        pip install pyyaml
        curl -sL https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -o /usr/local/bin/yq
        chmod +x /usr/local/bin/yq

    # Step 3: Read config.yaml and create .config
    - name: Generate .config from config.yaml
      run: |
        python3 - <<EOF
        import yaml
        import os

        # Load the YAML configuration
        with open("config.yaml", "r") as file:
            config = yaml.safe_load(file)

        # Prepare the config path
        config_path = os.path.join(os.getcwd(), "openwrt", ".config")

        # Open the .config file to write
        with open(config_path, 'w') as config_file:
            for package in config.get("packages", []):
                config_file.write(f"CONFIG_PACKAGE_{package['name']}=y\n")

        EOF

    # Step 4: Build the package
    - name: Build package
      run: |
        cd openwrt
        make defconfig
        make package/${PACKAGE_NAME}/compile V=s

    # Step 5: Upload the resulting .ipk file
    - name: Upload .ipk package
      uses: actions/upload-artifact@v3
      with:
        name: ipk-package
        path: openwrt/bin/packages/*/*.ipk
