name: Build OpenWrt Project

on:
  workflow_dispatch:  # شروع به صورت دستی

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up OpenWrt environment
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev gawk git zlib1g-dev
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          
      - name: Clone the project from GitHub (using config.yaml)
        run: |
          PROJECT_URL=$(yq eval '.project_url' config.yaml)
          git clone $PROJECT_URL openwrt/project

      - name: Generate OpenWrt .config file
        run: |
          python3 scripts/generate_config_from_yaml.py config.yaml openwrt/.config

      - name: Build the project for OpenWrt
        run: |
          cd openwrt
          make defconfig
          make V=s  # یا هر دستور خاص برای ساخت

      - name: Upload .ipk files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ipk-artifact
          path: openwrt/bin/packages/*/*.ipk
          if-no-files-found: warn
