name: Build app for OpenWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up OpenWrt build environment
      - name: Set up OpenWrt build environment
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk flex git wget
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install luci

      # Step 3: Clone your custom repository and add the package
      - name: Clone custom repository and add package
        run: |
          cd openwrt
          git clone https://github.com/peditx/luci-theme-peditx package/luci-theme-peditx
          echo "Package added successfully"

      # Step 4: Ensure .config is created correctly
      - name: Ensure .config exists and is correct
        run: |
          cd openwrt
          if [ ! -f .config ]; then
            make defconfig
          fi
          
      # Step 5: Set OpenWrt configuration
      - name: Set OpenWrt configuration
        run: |
          cd openwrt
          # Make sure to replace the config file with the one from the repository
          cp ${{ github.workspace }}/config.yaml .config

      # Step 6: Build the package
      - name: Build package
        run: |
          cd openwrt
          make package/luci-theme-peditx/compile V=s

      # Step 7: Upload the compiled package
      - name: Upload compiled package
        uses: actions/upload-artifact@v3
        with:
          name: luci-theme-peditx.ipk
          path: openwrt/bin/targets/*/*/packages/*.ipk
