name: Build app for OpenWrt

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies (yq, python packages)
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl python3-pip
        python3 -m pip install --upgrade pip
        pip install pyyaml

        # Install yq
        curl -s https://api.github.com/repos/mikefarah/yq/releases/latest \
        | jq -r '.assets[] | select(.name | test("yq_.*_linux_amd64")) | .browser_download_url' \
        | xargs curl -LO
        sudo chmod +x yq_*.linux.amd64
        sudo mv yq_*.linux.amd64 /usr/local/bin/yq

    # Step 4: Create .config from config.yaml
    - name: Create .config from config.yaml
      run: |
        python3 ${GITHUB_WORKSPACE}/scripts/generate_config_from_yaml.py ${GITHUB_WORKSPACE}/config.yaml ${GITHUB_WORKSPACE}/openwrt/.config

    # Step 5: Build the package
    - name: Build package
      run: |
        cd openwrt
        make package/${PACKAGE_NAME}/compile V=s

    # Step 6: Upload the generated ipk as artifact (Updated to use v3)
    - name: Upload ipk as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ipk-artifact
        path: openwrt/bin/packages/*/*.ipk
