name: Build app for OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Required Tools
      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev \
            gawk git gettext libssl-dev xsltproc wget unzip python3 python3-distutils zip
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      # Step 3: Read Config File and Extract Values
      - name: Read Config File
        id: config
        run: |
          export REPOSITORY=$(yq '.repository' config.yaml)
          export PACKAGE_NAME=$(yq '.package_name' config.yaml)
          export ARCHITECTURES=$(yq '.architectures | join(",")' config.yaml)
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "ARCHITECTURES=$ARCHITECTURES" >> $GITHUB_ENV

      # Debug step for confirmation
      - name: Debug Config Values
        run: |
          echo "Repository: ${{ env.REPOSITORY }}"
          echo "Package Name: ${{ env.PACKAGE_NAME }}"
          echo "Architectures: ${{ env.ARCHITECTURES }}"

      # Step 4: Clone the Package Repository
      - name: Clone Package Repository
        run: |
          git clone "${{ env.REPOSITORY }}" ./package-src

      # Step 5: Build Package for Each Architecture
      - name: Build Packages
        run: |
          mkdir -p openwrt
          cd openwrt
          for ARCH in $(echo "${{ env.ARCHITECTURES }}" | tr ',' ' '); do
            echo "Building for $ARCH..."
            make target=$ARCH
          done

      # Step 6: Create Zip File with .ipk Packages
      - name: Create Zip File with IPK Files
        run: |
          mkdir -p build_outputs
          for ARCH in $(echo "${{ env.ARCHITECTURES }}" | tr ',' ' '); do
            mkdir -p build_outputs/$ARCH
            # Copy the .ipk files generated during the build
            cp ./openwrt/bin/packages/*/$ARCH/*.ipk build_outputs/$ARCH/
          done
          zip -r package_builds.zip build_outputs

      # Step 7: Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt-Packages
          path: package_builds.zip
