name: Build app for OpenWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up OpenWrt build environment
      - name: Set up OpenWrt build environment
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk flex git wget
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install luci

      # Step 3: Clone custom repository and add the package
      - name: Clone custom repository and add package
        run: |
          cd openwrt
          # Loop over repositories in config.yaml and clone them dynamically
          for repo in $(yq eval '.repositories[]' ${GITHUB_WORKSPACE}/config.yaml); do
            git clone $repo package/$(basename $repo)
          done

      # Step 4: Generate .config from config.yaml dynamically
      - name: Generate .config from config.yaml
        run: |
          cd openwrt
          if [ ! -f .config ]; then
            echo "Creating .config from config.yaml"
            python3 generate_config_from_yaml.py ${{ github.workspace }}/config.yaml .config
          fi

      # Step 5: Build packages dynamically from config.yaml
      - name: Build package
        run: |
          cd openwrt
          # Loop over package names in config.yaml and build them dynamically
          for package in $(yq eval '.packages[]' ${GITHUB_WORKSPACE}/config.yaml); do
            echo "Building $package..."
            make package/$package/compile V=s
          done

      # Step 6: Upload the compiled packages
      - name: Upload compiled package
        uses: actions/upload-artifact@v3
        with:
          name: compiled-packages
          path: openwrt/bin/targets/*/*/packages/*.ipk
