name: Build app for OpenWrt

on:
  workflow_dispatch:  # شروع دستی

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl python3-pip jq
        python3 -m pip install --upgrade pip
        pip install pyyaml

        # Install yq
        YQ_URL="https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64"
        curl -LO "$YQ_URL"
        sudo chmod +x yq_linux_amd64
        sudo mv yq_linux_amd64 /usr/local/bin/yq

    - name: Create .config from config.yaml
      run: |
        mkdir -p openwrt
        python3 ${GITHUB_WORKSPACE}/scripts/generate_config_from_yaml.py ${GITHUB_WORKSPACE}/config.yaml ${GITHUB_WORKSPACE}/openwrt/.config

    - name: Build package
      run: |
        cd openwrt
        PACKAGE_NAME=$(yq eval '.package_name' ${GITHUB_WORKSPACE}/config.yaml)
        make package/${PACKAGE_NAME}/compile V=s

    - name: Upload ipk as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ipk-artifact
        path: openwrt/bin/packages/*/*.ipk
