name: Build app for OpenWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up OpenWrt build environment
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk flex git wget
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install luci

      - name: Clone custom repository and add package
        run: |
          cd openwrt
          git clone ${{ secrets.REPOSITORY }} package/luci-theme-peditx
          echo "Package added successfully"

      - name: Configure OpenWrt build
        run: |
          cd openwrt
          cp ${{ github.workspace }}/config.yaml .config
          make defconfig

      - name: Build package
        run: |
          cd openwrt
          make package/$PACKAGE_NAME/compile V=s

      - name: Upload compiled package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ secrets.PACKAGE_NAME }}.ipk
          path: openwrt/bin/targets/*/*/packages/*.ipk
