name: "Build Theme | OpenWrt SDK"

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Enter the GitHub repository URL of the theme'
        required: true
        default: 'https://github.com/peditx/luci-theme-peditx'

jobs:
  build-theme:
    name: Build Theme from Provided URL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/21.02.5/targets/x86/64/openwrt-sdk-21.02.5-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
          mkdir sdk
          tar -xf openwrt-sdk-21.02.5-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz -C sdk --strip-components=1

      - name: Clone Theme Repository
        run: |
          git clone ${{ github.event.inputs.repo_url }} luci-theme
          cp -r luci-theme sdk/package/

      - name: Configure SDK
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          echo "CONFIG_PACKAGE_luci-theme-peditx=m" >> .config
          

      - name: Build Theme
        run: |
          cd sdk
          ./scripts/feeds install luci-theme-peditx
           make defconfig
           make package/luci-theme-peditx/compile -j1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-themes
          path: |
            sdk/bin/packages/**/luci-theme*.ipk